name: Bug report (反馈 Bug)
description: Create a bug report to help HugeGraph improve
title: '[Bug] describe the main problem'
labels:
  - bug

body:
  - type: markdown
    attributes:
      value: |
        **Note (特别注意)**:
        1. We need as much detailed information as possible to reproduce the problem, the more detailed information (including logs/screenshots/configurations, etc.) will be responded and processed faster.
        我们需要尽可能**详细**的信息来**复现**问题, 越详细的信息 (包括**日志 / 截图 / 配置**等)会**越快**被响应和处理。
        2. Please keep the original template category (for example: [Bug]) for the Issue title. You can add blank lines or use serial numbers between long descriptions to keep the typesetting clear.
        Issue 标题请保持原有模板分类(例如:`[Bug]`), 长段描述之间可以增加`空行`或使用`序号`标记, 保持排版清晰。
        3. Please submit an issue in the corresponding module, lack of valid information / long time (>14 days) unanswered issues may be closed (will be reopened when updated).
        请在对应的模块提交 issue, 缺乏有效信息 / 长时间 (> 14 天) 没有回复的 issue 可能会被 **关闭**(更新时会再开启)。
  
  - type: dropdown
    attributes:
      label: Bug Type (问题类型)
      options:
        - gremlin (结果不合预期)
        - rest-api (结果不合预期)
        - dashboard render (前端渲染问题)
        - data inconsistency (数据不一致)
        - exception / error (异常报错)
        - others (please comment below)
  
  - type: checkboxes
    attributes:
      label: Before submit
      options:
        - label: I had searched in the [issues](https://github.com/hugegraph/hugegraph-loader/issues) and found no similar issues.
          required: true

  - type: textarea
    attributes:
      label: Environment (环境信息)
      description: >
        server version could get from [rest-api](https://hugegraph.apache.org/docs/clients/restful-api/) (http://localhost:8080/versions)
      value: |
        - Server Version: v0.12.x
        - Loader Version: v0.12.x
        - Data Size:  xx vertices, xx edges <!-- (like 1000W 点, 9000W 边) -->
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Expected & Actual behavior (期望与实际表现)
      description: |
        we can refer [How to create a minimal reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example), if possible, please provide screenshots or GIF.
        可以参考 [如何提供最简的可复现用例](https://stackoverflow.com/help/minimal-reproducible-example)，请提供清晰的截图, 动图录屏更佳。
      placeholder: |
        type the main problem here 
        
        ```java
        // Detailed exception / error info (尽可能详细的日志 + 完整异常栈)

        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Vertex/Edge example (问题点 / 边数据举例)
      description: |
        If the question is related to specific point/edge data, please provide the full `raw data REST-API query result`.
        (如果问题与具体的点 / 边数据相关, 请提供完整的`原始数据 + REST-API 查询结果`)
      placeholder: |
        // Origin data
        tom  18  boy  HK

        // JSON of Vertex / Edge
        {
          "vertex": { "id": "xxx" }
        }
      render: javascript

  - type: textarea
    attributes:
      label: Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)
      description: |
        If the problem is related to a specific point type/edge type/index type, please provide the full Schema.
        (如果问题与具体的点类型 / 边类型 / 索引类型相关, 请提供完整的 `Schema 返回 JSON 结果`)
      placeholder: |
        // Query URL
        GET http://localhost:8080/graphs/hugegraph/schema/vertexlabels

        // JSON of GraphSchema
        {
          "vertex": { "id": "xxx" }
        }
      render: javascript
