name: hugegraph-loader ci

on:
  push:
    branches:
      - master
      - /^release-.*$/
      - /^test-.*$/
      - gh-pre-release
      - gh-master
  pull_request:
    branches:
      - master
      - /^release-.*$/
      - /^test-.*$/
      - gh-pre-release
      - gh-master

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      TRAVIS_DIR: assembly/travis
      STATIC_DIR: assembly/static
      COMMIT_ID: e65641517361d7da7ef1801489c15e3af7863a39
      BRANCH_ID: gh-master
      DB_USER: root
      DB_PASS: root
      DB_DATABASE: load_test
    steps:
      - name: Install JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Compile
        run: |
          mvn install:install-file -Dfile=$STATIC_DIR/lib/ojdbc8-12.2.0.1.jar -DgroupId=com.oracle -DartifactId=ojdbc8 -Dversion=12.2.0.1 -Dpackaging=jar
          mvn install:install-file -Dfile=$STATIC_DIR/lib/hugegraph-client-1.9.7.jar -DgroupId=com.baidu.hugegraph -DartifactId=hugegraph-client -Dversion=1.9.7 -Dpackaging=jar
          mvn compile -Dmaven.javadoc.skip=true | grep -v "Downloading\|Downloaded"

      - name: Prepare env and service
        run: |
          $TRAVIS_DIR/install-hadoop.sh
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASS }}
          $TRAVIS_DIR/install-hugegraph-from-source.sh $BRANCH_ID | grep -v "Downloading\|Downloaded"

      - name: Run test
        run: |
          mvn test -P unit
          mvn test -P file
          mvn test -P hdfs
          mvn test -P jdbc

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: target/jacoco.xml
